// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fovvmfvtgrheiqchaqml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvdnZtZnZ0Z3JoZWlxY2hhcW1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTc5OTYsImV4cCI6MjA3Mzg3Mzk5Nn0.wNPwCdskwWxE6HGotOvpJVLzcc_9JnhJgcfQT0YmS4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});